############################################################################### 
# Author: Agustin Bassi 
# Date: October 2020 
# Copyright: Agustin Bassi
# Project: Nodes-Connection
# Brief: TODO: Describe it 
#
# To attach to mosquitto clients running into mosquitto container run:
#
#   - docker exec -it mosquitto mosquitto_sub -t "#"
#   - docker exec -it mosquitto mosquitto_pub -t "greet" "hello nodes-connection"
#
###############################################################################
  
version: '3'

services:

  mosquitto:
    image:          eclipse-mosquitto:latest
    hostname:       mosquitto
    container_name: mosquitto
    volumes:
      -             ./mqtt-broker/config:/mosquitto/config
      # -             ./mqtt-broker/certs:/mosquitto/certs
    networks:
      -             nodes-connection-network 
    expose:
      -             "1883"
      -             "8883"
      -             "9001"
    ports:
      -             "1883:1883"
      -             "8883:8883"
      -             "9001:9001"


networks:
  nodes-connection-network:
    driver: bridge