############################################################################### 
# Author: Agustin Bassi 
# Date: October 2020 
# Copyright: Agustin Bassi
# Project: Nodes-Connection
# Brief: TODO: Describe it 
#
# To attach to mosquitto clients running into mosquitto container run:
#
#   - docker exec -it mosquitto mosquitto_sub -t "#"
#   - docker exec -it mosquitto mosquitto_pub -t "greet" "hello nodes-connection"
#
###############################################################################
  
version: '3'

services:

  nodered:
    image:                    nodered/node-red
    hostname:                 nodered
    container_name:           nodered
    volumes:
      -                       ./nodered:/data
    networks:
      -                       nodes-connection-network 
    ports:
      -                       "1880:1880"
    depends_on:
      -                       mysql-server
        
  mosquitto:
    image:                    eclipse-mosquitto:latest
    hostname:                 mosquitto
    container_name:           mosquitto
    volumes:
      -                       ./mqtt-broker/config:/mosquitto/config
      # -                     ./mqtt-broker/certs:/mosquitto/certs
    networks:
      -                       nodes-connection-network 
    expose:
      -                       "1883"
      -                       "8883"
      -                       "9001"
    ports:
      -                       "1883:1883"
      -                       "8883:8883"
      -                       "9001:9001"

  mysql-server:
    image:                    mysql:5.7
    hostname:                 mysql-server
    container_name:           mysql-server
    environment:
        MYSQL_ROOT_PASSWORD:  userpass
    volumes:
        -                     ./db/dumps:/docker-entrypoint-initdb.d
        -                     ./db/data:/var/lib/mysql
    networks:
        -                     nodes-connection-network
    ports:
      -                       "3306:3306"

  mysql-admin:
    image:                    phpmyadmin/phpmyadmin
    hostname:                 mysql-admin
    container_name:           mysql-admin
    environment: 
        PMA_HOST:             mysql-server
        PMA_PORT:             3306
        MYSQL_ROOT_PASSWORD:  userpass
    networks:
        -                     nodes-connection-network
    depends_on:
        -                     mysql-server
    ports:
        -                     "1881:80"

networks:
  nodes-connection-network:
    driver:                   bridge